### ISSUE TITLE
Fix: Change indexer table

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#107]
# Description

Indexer Apibar crashed when redeploy because already existing rows are rescraped for the last block.
Maybe a Try catch can be useful (not sure that's not gonna be crashed also but maybe).

- [ ] Change indexer table PRIMARY KEY to an index auto increment (fast fixed)
- [ ] Check if we can do get of the last block scraped before redeploy of the indexer? Maybe Apibara V2 fixes this.
- [ ] Verify if we rerun the indexer, things are saved.
- [ ] Verify rows in DB for every tables: in local, good if we can try on a cloud host postgres DB to simulate the prod env too
- [ ] Change the Backend endpoints to check

**Comment by EjembiEmmanuel** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I'd love to work on this

ETA: EOD
