### ISSUE TITLE
Fix endpoints & indexer

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#110]
# Description

Do something robust and well tested, please.

- [ ] Fix all endpoints in apps/data-backend. Getting issue when send BigInt value, please convert or select the needed attributes in each endpoints.
- [ ] Check and fix if needed every endpoint based on the need for the frontend.
- [ ] Verify all endpoints, data in Postgres for an indexer.
- [ ] Verify the backend can be used to be integrate in the Launchpad frontend UI in the webapp. We need it asap.

**Comment by EjembiEmmanuel** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I'd love to work on this

ETA: EOD
