### ISSUE TITLE
Fastify Backend and Fix prod deployment for Fastify

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#119]
- [ ] Fastify backend
- [ ] Deployment Fastify backend
- [ ] Fixed backend endpoints of indexer

@EjembiEmmanuel

**Comment by EjembiEmmanuel** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Kindly assign
