### ISSUE TITLE
Fix solidity test vault BTC

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#132]
# Description

Fix solidity test vault BTC here:

https://github.com/AFK-AlignedFamKernel/afk_monorepo/blob/main/onchain/solidity_contracts/test/Vault.t.sol

**Comment by ShantelPeters** [comment]
Hi

**Comment by Jemiiah** [comment]
@MSghais i would to work on this issue when OD Havm starts

**Comment by Jemiiah** [comment]
@MSghais i would to work on this issue when OD Havm starts

**Comment by estherbreath** [comment]
@MSghais Could you assign me this issue, please?


To fix the Solidity test for the Vault BTC contract, I will do the following:
    1. Initialize the vault correctly using the initialize function with the WBTC token address. 
    2. Ensure proper role assignments for the admin address using the hasRole function checks. 
    3. Verify token balances after minting operations using the balanceOf function.

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hello I'm a blockchain and also a frontend developer and I would love to work on this issue

**Comment by tevrat-aksoy** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
hello, I am smart contract developer with 2 year experience on defi projects. I want work on this issue.

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I would love to work on this issue I have experience on solidity issue and would be able to work on this issue

### How I plan on tackling this issue
atm ETA : 48 hours to tackle this issue

**Comment by thesledge04** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have experience working with Solidity contracts and testing, which equips me to efficiently identify and resolve issues in smart contract test cases. My knowledge of blockchain development best practices will help ensure the tests are robust and maintainable.

### How I plan on tackling this issue
Review and run the tests to identify issues.
Fix logic and setup errors in the test code.
Ensure external dependencies are properly mocked.
Re-run the tests to confirm fixes.
Document changes for clarity.

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have experience in building an EVM explorer and indexer and a good understanding of the Solidity language.
https://github.com/walnuthq/op-scan

### How I plan on tackling this issue
I will carefully read the BTC Vault tests and understand what needs to be fixed.
I will then implement the fixes and make sure every tests pass correctly again.

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum ecosystem.

### How I plan on tackling this issue
I had written the Vault contract and initial tests. I would love to fix the tests and make it completely working

**Comment by estherbreath** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a smart contract developer in Solidity and Cairo.

As a smart contract developer in Solidity and Cairo, I will leverage my background to solve this issue by:
Analyzing the Vault.t.sol test file for logical errors and implementing proper initialization of the vault contract. Writing comprehensive test cases to cover various scenarios, including token minting and balance verification.


### How I plan on tackling this issue

To fix the Solidity test for the Vault BTC contract, I will do the following:
       Initialize the vault correctly using the initialize function with the WBTC token address. 
       Ensure proper role assignments for the admin address using the hasRole function checks. 
       Verify token balances after minting operations using the balanceOf function.
