### ISSUE TITLE
NIP-4 private message hooks

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#134]
# Description

Nostr NIP-4 messages hooks and integrate too the UI already existing.

NIP-4 docs:
https://github.com/nostr-protocol/nips/blob/master/04.md

- [ ] Create all hooks with tanstack in the afk_nostr_sdk located in /packages
- [ ] Integrate the hooks in the existing UI and made the modifications to be compatible with the hooks made

**Comment by ShantelPeters** [comment]
Hi

**Comment by od-hunter** [comment]
C

**Comment by od-hunter** [comment]
Hi @MSghais , please can I be assigned this when od hack starts?

**Comment by NueloSE** [comment]
@MSghais can i work on this issue

**Comment by addegbenga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
A frontend engineer with over 5 years experience.

### How I plan on tackling this issue
I will tackle this issue by:
- Looking at nip-4 docs 
- Creating a private message hook based on the docs
- Integrating this hooks to the existing UI

ETA: 72hrs

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Please can I be assigned this issue? This would be my first time contributing to this ecosystem and I’d love to be given the opportunity. I am a  blockchain Developer, and my experience includes html, css, react, JavaScript,TypeScript and solidity and Cairo.

### How I plan on tackling this issue
To solve this issue, I’d take the following steps:
1.⁠ ⁠I’ll understand NIP-4 for encrypted messages to guide hook development.
2.⁠ ⁠I’ll develop useQuery and useMutation hooks in afk_nostr_sdk for sending and fetching messages.
3.⁠ ⁠Replace existing message handling logic with the new hooks in the UI components.
4.⁠ ⁠I’ll refactor the UI for compatibility with the new hooks and update state and error handling as needed.
5.⁠ ⁠⁠Lastly, I’ll verify message sending/receiving works correctly in the UI across scenarios.

Please assign this issue to me.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
HI i am Shantel a frontend and blockchain developer with vast knowledge with languages like Typescript,javascript,Cario just to name a few . i will love to work on this issue . please kindly assign i am avaliable to work 

### How I plan on tackling this issue
To approach the problem i will debug step by step to isolate specific problems

1. Check EVMProviders Setup: Ensure the EVMProviders configuration is correctly implemented.
2. siwe-auth Integration: Verify the proper integration of siwe-auth for wallet authentication.
3. WalletConnect Integration: Ensure WalletConnect is properly integrated into the app.
4. Screen EVM Connect: Implement the EVM connection screen by invoking EVMProviders and WalletConnect.
5.  Add to UI: Ensure the UI elements for EVM wallet integration are correctly placed within your app’s wrapper component.
