### ISSUE TITLE
Videos short view scroll Screen and Components

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#171]
# Description

Tiktok screens scroll for video.
Do it in the Mobile repo.

Create screen, module, and components to have a way to scroll video or short video with a Nostr event NIP-71 or NIP-1:

https://github.com/nostr-protocol/nips/blob/master/71.md

- [ ] Tiktok module with Flatlist with smooth scroll
- [ ] Video component for Nostr NIP-1 or NIP-71 with specific video metadata
- [ ] Nostr interactions to the video
- [ ] Add ShortsVideo screen in the router using the ShortVideoModule

![image](https://github.com/user-attachments/assets/9c4bc5c7-0e36-4a06-b2e1-8a23a8eb4e30)

**Comment by ShantelPeters** [comment]
Hi @MSghais can I be assigned to this issue ?

**Comment by devcollinss** [comment]
@MSghais I'd like to take on this task in the mobile repo. Here's my approach with an estimated completion time of 30 hours:

    Create the ShortsVideo screen:
    I'll set up a new screen for short videos and link it to the router using the ShortVideoModule.

    Build the TikTok module:
    I'll use FlatList to create a scrollable list for users to smoothly navigate through the videos.

    Develop the Video component:
    I'll fetch video metadata using NIP-1 or NIP-71 and ensure the component renders videos correctly with the relevant details.

    Add Nostr interactions:
    I'll implement user interactions (likes, comments, etc.) using Nostr events to allow engagement with the videos.

Let me know if I can go ahead!

ETA 30hrs

**Comment by NueloSE** [comment]
@MSghais can i work on this

**Comment by lindsaymoralesb** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Lindsay - Software Engineer. 4.5+ years of exp. Already contributed to this project several times.

### How I plan on tackling this issue
1. Create the short videos module.
2. Create the view videos component using the FlatList as stated on the description, ensuring a smooth scroll and also handling video playback based on visibility.
3. Create a video component that accepts Nostr event data as props.
4. Implement the integration with the nostr hooks by adding buttons for the different interactions with the videos.
5. Add the screen in the router.
6. Testing and demo video.

**Comment by Benjtalkshow** [comment]
Hello @MSghais 
Can i be assigned to this task? ETA 48hrs

**Comment by petersdt** [comment]
@MSghais  can i be assigned this task?
