### ISSUE TITLE
Video Nostr

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#186]
# Description

We need to finish Nostr video, create and view:

- [ ] Upload the video into Pinata (add Pinata API KEY in .env in the website repo and run it)
- [ ] If type of File is a video in the CreateForm: Use the createVideo hook and correctly add all tags needed as described in NIP-71: 
https://github.com/nostr-protocol/nips/blob/master/71.md

- [ ] Add a Nostr video component to render a Video in the Feed like it: 

![image](https://github.com/user-attachments/assets/24cb9c45-2b9c-4026-95b7-1d000efb76b2)

- [ ] Add the Kind Video in the /Feed and filter search kind by default, and render the new VideoComponent, you can read the video like the NostrVideo component or redirect to a ShortScreen created

**Comment by akintewe** [comment]
Hello @MSghais please can i be assigned this task, it will be done as soon as possible

**Comment by MSghais** [comment]
> Hello @MSghais please can i be assigned this task, it will be done as soon as possible

Hello, what's your skills in React Native + Expo Typescript etc? Can you apply in Only Dust with an ETA etc? Let's also discuss in Telegram, please join and ping me @akintewe

**Comment by 0xdevcollins** [comment]
Hello @MSghais can I work on this?

**Comment by MSghais** [comment]
> Hello @MSghais can I work on this?

Apply on OD with an ETA and Xp and plan to tackle the issue please

**Comment by akintewe** [comment]
> > Hello @MSghais please can i be assigned this task, it will be done as soon as possible
> 
> Hello, what's your skills in React Native + Expo Typescript etc? Can you apply in Only Dust with an ETA etc? Let's also discuss in Telegram, please join and ping me @akintewe

alright thank you so much @MSghais  please can i get the telegram link

**Comment by MSghais** [comment]
> > > Hello @MSghais please can i be assigned this task, it will be done as soon as possible
> > 
> > 
> > Hello, what's your skills in React Native + Expo Typescript etc? Can you apply in Only Dust with an ETA etc? Let's also discuss in Telegram, please join and ping me @akintewe
> 
> alright thank you so much @MSghais please can i get the telegram link

https://t.me/afk_aligned_fam_kernel

**Comment by akintewe** [comment]
> > > > Hello @MSghais please can i be assigned this task, it will be done as soon as possible
> > > 
> > > 
> > > Hello, what's your skills in React Native + Expo Typescript etc? Can you apply in Only Dust with an ETA etc? Let's also discuss in Telegram, please join and ping me @akintewe
> > 
> > 
> > alright thank you so much @MSghais please can i get the telegram link
> 
> https://t.me/afk_aligned_fam_kernel

thank you,

**Comment by akintewe** [comment]
> I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).
> 
> ### My background and how it can be leveraged
> I am qualified to take on the Nostr video implementation challenge since I am a software engineer with four years of experience in Go, JavaScript, Solidity, Cairo, and TypeScript in addition to a Bachelor of Science in Computer Science. My scholarly background and practical exposure to these languages offer a strong foundation for comprehending and applying the necessary characteristics.
> 
> ### How I plan on tackling this issue
> In order to tackle this issue, I would begin by incorporating the Pinata API for video uploads, making sure that the API key is stored securely in the.env file. Then, using the createVideo hook and the required tags as outlined in NIP-71, I would adapt the CreateForm component to handle video file formats. I would create a new NostrVideo component to produce videos and display them in the Feed in accordance with NIP-71 standards. In order to provide users with a more immersive experience, I would incorporate the new VideoComponent and update the Feed component to include a Kind Video filter. This would allow users to view movies inline or redirect to a dedicated ShortScreen.

@MSghais  Done :)

**Comment by MSghais** [comment]
@akintewe, do you have an Estimate Time of Arrival for this issue?
Pretty urgent, maybe a main contrib in the repo can take it tomorrow. Let me know, I can find also others issues, ping me on Telegram in DM

**Comment by akintewe** [comment]
> @akintewe, do you have an Estimate Time of Arrival for this issue? Pretty urgent, maybe a main contrib in the repo can take it tomorrow. Let me know, I can find also others issues, ping me on Telegram in DM

i can finish it within a day :)

**Comment by MSghais** [comment]
Like a PR tomorrow night? Beast mode, that's the kind of dev I need to work on atm, appreciate ;)
Also ping me, need to discuss a bit

**Comment by akintewe** [comment]
> Like a PR tomorrow night? Beast mode, that's the kind of dev I need to work on atm, appreciate ;) Also ping me, need to discuss a bit

no problem, i am here for the task, ok ill ping you on telegram

**Comment by akintewe** [comment]
i just sent you a message @MSghais  :)

**Comment by addegbenga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a frontend engineer with over 5 years experience.

### How I plan on tackling this issue
- I will check for type when creating note and if its a video I will use the createVideo hook.
- I will add Video kind to the feed view so users can see video component as well

**Comment by Baronvil** [comment]
Would love to tackle this!
