### ISSUE TITLE
Art-Peace : Indexer & Backend

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#193]
# Description

- [ ] Test Art-peace backend in /backend/indexer indexer with Webhook
- [ ] Update the readme to deploy easily the indexer in Railway like others indexer script
- [ ] Check if the webhook correctly update the backend endpoint: /consume-indexer-msg
- []  Test the frontend in /apps/pwa
- [] Check all endpoint are working: /place-pixel for example never receive the jsonBody

**Comment by EjembiEmmanuel** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Kindly assigned as discussed @MSghais

ETA: <24hrs
