### ISSUE TITLE
Test Art peace to snforge correct version

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#197]
# Description 

I've added the artpeace test Cairo in onchain/cairo/tests/art_peace_tests.cairo.

We need to upgrade the snforge version and all the tests with the current one.

- [ ] Uncomment the import in the lib.cairo tests of the art_peace_tests
- [ ] Upgrade with the current version of snforge
- [ ] Change tests if different way to do the tests

**Comment by manlikeHB** [comment]
Hi @MSghais, can i work on this?
