### ISSUE TITLE
Contacts for Cashu & Private message

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#203]
# Description

Create a management of Contacts with NIP-5 and Nostr address.
This component need to be added in the Private message, and Cashu Wallet.
We already have the types and storage to used for the Contact type. We used Localstorage atm.

Screens of what we need to have:

![image](https://github.com/user-attachments/assets/e8330cca-d160-46e8-8a23-716e61c9ec5d)

![image](https://github.com/user-attachments/assets/2ab4a5a6-6359-412d-bfc6-fe8d4b747311)

![image](https://github.com/user-attachments/assets/fab9ca7b-e624-4d2e-bfe4-8452ef88a690)

**Comment by akintewe** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
As a Computer Science graduate with practical expertise in JavaScript and TypeScript, I'm enthused about this frontend development opportunity. My expertise includes experience with online apps and state management, which complements this contact management capability.

### How I plan on tackling this issue
Starting with the existing contact types and localStorage implementation, I'd design a modular component structure that could be shared by the Private Message and Cashu Wallet interfaces. I intend to build a clean UI for contact management that will handle both NIP-5 and Nostr addresses with correct validation. The system would contain:

Contact list view with search functionality.
Create/edit contact forms with field validation.
Seamless connection with the existing local storage structure.
Responsive design for desktop and mobile devices

**Comment by KevinMB0220** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hi, I'm part of Dojo Coding. For this task, I will create a contact management component that supports NIP-5 and Nostr addresses. The component will be integrated into the Private Messaging and Cashu Wallet sections. I'll make use of the existing contact types and local storage as shown in the provided designs. The functionality will include adding, removing, and viewing contacts, ensuring a smooth user experience while handling Nostr profiles and related data.

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
i have experience in blockchain previously as personal projects and OS, so hoping to make use of them here and mark my first odhack contribution

**Comment by jancris100** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I'm from dojo coding with 2 year of experience in differents backend Developer lenguage

### How I plan on tackling this issue
1. User clicks “Add Contact”.


2. User fills in the details (Name, NIP-5, Nostr Address).


3. Data is validated and saved in LocalStorage.


4. Contacts List is updated with the new contact.



Selecting Contact in Private Messages or Wallet:

1. User opens the contact picker when sending a message or transaction.


2. Contacts stored in LocalStorage are displayed.


3. Upon selection, the Nostr address is automatically populated for the message or transaction.

**Comment by MrRoudyk** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Software Engineer with 10 years of experience. For the past 5 years, I’ve specialized in HR Tech solutions, now used by tens of thousands of companies and hundreds of thousands of users. I have also contributed to open source development at OnlyDust ([My OnlyDust Profile](https://app.onlydust.com/u/MrRoudyk)). 

I’m passionate about exploring new technologies and currently looking to deepen my expertise in blockchain, smart contracts, and decentralized applications.

### How I plan on tackling this issue
First, I will review the existing data types and how contacts are stored in LocalStorage. Then, I will create an interface to manage contacts with support for NIP-5 and Nostr addresses. After that, I will integrate this component into the Private Message and Cashu Wallet sections. Finally, I will conduct testing to ensure everything works correctly.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
 I have extensive experience in front-end development, particularly in building user interfaces that manage and display data effectively. My work with blockchain applications has equipped me with the skills to handle address management and local storage efficiently.

### How I plan on tackling this issue
I will implement a contacts management component by leveraging existing types and local storage for data persistence. This will involve creating a user-friendly interface within the Private Message and Cashu Wallet sections to add, view, and manage contacts with NIP-5 and Nostr addresses. I will ensure the design aligns with the current application style, followed by thorough testing to guarantee functionality and usability.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am go dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.
