### ISSUE TITLE
Finish Subscription payment Nameservice

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#204]
# Description 

AFK nameservice, like ENS/STARK.ID Nft for AFK:

This PR is already started, you can start the work in identity/nameservice.cairo.

- [ ] Upgradeable contract
- [ ] Access control 
- [ ] AFK Nameservice subscription for one year with YOUR_NAME.afk.
- [ ] Setup a amount of token to buy a yearly subscription.
- [ ] Create test for yearly subscription

Bonus: 
Simple UI in the mobile form

**Comment by od-hunter** [comment]
Hi @MSghais , can I work on this please

**Comment by Mystic-Nayy** [comment]
@MSghais Can i be assigned to work on this?

**Comment by 0xNeshi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Creator and maintainer of Cairo learning track on Exercism. Regular "Cairo Book" and "Starknet By Examle" contributor. Wrote and maintained production-level Solidity contracts, including integrating a protocol with Beefy Vaults. Developer with 6 years of experience, 3 of which in the Web3 space.

### How I plan on tackling this issue
- investigate how Starknet.id implements nameservice logic
- create the contract; make yearly subscription amount configurable by the owner
(although the description states there is a PR, a quick search of the repository yielded no PRs working on this. Maybe it's not pushed?)
- add extensive tests to _/onchain/cairo/src/tests/_

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
i have experience in blockchain previously as personal projects and OS, so hoping to make use of them here and mark my first odhack contribution

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a go dev. A new-comer here, willing and ready to contribute to contribute to solve the issue.

**Comment by jaiminRaiyani** [comment]
Can I jump on this task?

**Comment by PoulavBhowmick03** [comment]
Is it okay if I take this?
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.

### My Approach

I will complete this Nameservice subscription in `identity/nameservice.cairo` by implementing a yearly subscription function that registers `YOUR_NAME.afk` and processes payments with a token fee. i will ensure the contract is upgradeable and apply access control for authorized modifications. Additionally, I’ll add tests to cover the changes. And after that I will try to work on the UI if possible

I also have an extensive experience of contributing to this project multiple times, I can get this done well

### ETA - 3 days
