### ISSUE TITLE
Fix nameservice AFK tests

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#267]
# Description

Fix nameservice tests import and nameservice.

- [ ] Fix nameservice aft tests
- [ ] Reimport it in the lib.cairo in the tests mod.
- [ ] Fix the test interfaces.
- [ ] Check if nameservice is ok.
- [ ] Do more tests if needed

**Comment by estherbreath** [comment]
I would like to work on this issue.

As a smart contract developer proficient in Cairo and Solidity, here's how I can tackle this issue 

I will review the current Nameservice contract implementation in Cairo, identifying and fixing any issues with test imports and interfaces. 

Re import necessary libraries in the test module, ensuring all required components are accessible. 

Update test interfaces to align with the latest contract structure. 

Conduct thorough testing to verify Nameservice functionality. 

Write additional test cases if needed to ensure comprehensive coverage.

**Comment by hakymulla** [comment]
can i take this?

**Comment by hakymulla** [comment]
Could I be assigned to this?
ETA: <48hrs
