### ISSUE TITLE
Pump Card UI Launch

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#27]
Improve the UI of the Pump card screen:

Component: TokenLaunchCard

Let's made simple things until a UI/UX Figma.

Viewable on the Games screen, select the PUMP tab:

Screen

![image](https://github.com/user-attachments/assets/0dceb4a6-ecfa-410f-a963-0e492c4720d4)

**Comment by od-hunter** [comment]
U

**Comment by martinvibes** [comment]
can i work on this @MSghais

**Comment by lauchaves** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hey! I'm Lau Chaves, and I would like to contribute to this issue!


I have over 5 years of experience working with JavaScript, React, and TypeScript, ruby... Im also part of Dojo Coding Costa Rica!

My primary role has been as a front-end developer, and I have a keen eye for detail and a strong focus on mobile-first approaches. I ensure the quality of my work through rigorous self- QA processes. I have a solid knowledge of CSS, Sass, and styled-components.

Feel free to check my onlydust profile here and github profile: lauchaves!


### How I plan on tackling this issue
For this issue, Id follow these steps: 

- Review the current UI.
- Identify and improve components or add new ones, like a card component that we can reuse to keep a consistent style.
- Add some padding and adjust spacing for better readability.
- Adjust buttons so they fit nicely with the card.

**Comment by GoSTEAN** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
With experience in web development and UI/UX design, I bring a strong understanding of creating intuitive and visually appealing interfaces. My skills in React and component-based design will help streamline and enhance the TokenLaunchCard component, ensuring a more engaging and user-friendly experience on the Games screen.

### How I plan on tackling this issue
Approach to the Problem:
Analyze Current Design:
Review the existing TokenLaunchCard component and understand its current functionality and user interaction. Identify any pain points or areas that may need improvement based on usability principles.
Simplify and Refine:
Start by simplifying the component’s layout and functionality. Focus on improving readability and clarity by adjusting spacing, typography, and color schemes. Ensure that important information is highlighted and easy to access.
Apply UI/UX Principles:
Implement basic UI/UX improvements such as better alignment, consistent padding, and visual hierarchy. Consider usability aspects like button sizes, hover effects, and responsive design to enhance the overall user experience.
Create a Figma Design:
Develop a Figma design based on the improved layout and UI/UX principles. This design will serve as a visual guide for further refinements and can be used to communicate the desired look and feel to stakeholders or team members.
Implement and Test:
Apply the design changes to the TokenLaunchCard component in the codebase. Test the updated UI to ensure it functions as expected and provides a better user experience. Gather feedback from users or team members to make any necessary adjustments.
This approach ensures that the TokenLaunchCard component is not only improved in terms of aesthetics but also in functionality, leading to a more engaging user experience.

**Comment by Supa-mega** [comment]
@MSghais i believe that i am more that capable to hop on this task considering my vast expertise in UI/UX and web development

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have 2 years of experience as a front-end developer, with expertise in JavaScript, React.js, CSS, and HTML. I've built full-stack projects like Crypto Bank, handling both front-end and back-end development. My skills in creating responsive, dynamic interfaces make me well-equipped to contribute effectively to your project.

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a web developer with over 6 years experience building applications both personal and professional projects. I started contributing to open source via onlydust in march this year and I have contributed to a couple of issues, you can see them in my profile.

### How I plan on tackling this issue
Simplify the UI of the pump card screen

**Comment by MSghais** [comment]
@od-hunter @Ayoazeez26 @GoSTEAN do you have an ETA?

@GoSTEAN do you have skills in Figma?

Thank you @lauchaves for giving us the ETA detailed.

**Comment by Ayoazeez26** [comment]
@MSghais an ETA of 1 day will suffice

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged

Hi @MSghais 
I'm interested in addressing the issue of improving the UI of the Pump card screen, specifically focusing on the TokenLaunchCard component. This is my first contribution to this project, but I bring 3 years of experience with frontend technologies, including Next.js, TypeScript, and Tailwind CSS. My background includes working on UI improvements for various projects like Opscan and the Blink extension.

### How I plan on tackling this issue
### Review and Refine UI Design

**Current State**: The Pump card screen displays details such as Coin Address, Owner, Supply, Price, and other token information.  
**Objective**: I will improve the visual presentation and usability of the `TokenLaunchCard` component based on the provided data.

### Simplify the UI

**Visual Improvements**:  
- I will use Tailwind CSS to update styles for better readability and visual appeal.
- I will ensure consistent spacing, alignment, and color schemes.

**Data Presentation**:  
- I will enhance the display of token details, making key information like Coin Address, Owner, Supply, Price, and Threshold Liquidity clearly visible and easy to understand.

### Integrate Extracted Data

**Content Integration**:  
- **Coin Address**: I will display this prominently.
- **Owner**: I will clearly indicate the token owner.
- **Supply, Price, Threshold Liquidity**: I will present these values in a structured format.
- **Quote Token and Step Increase**: I will ensure these details are included and easily accessible.
- **Token and Buy/Sell Actions**: I will provide buttons for actions like creating tokens and buying/selling, clearly labeled and functional.

### Technical Steps

**Update Styles**:  
- I will refactor the `TokenLaunchCard` component using Tailwind CSS to apply modern, responsive design principles.
- I will ensure the updated styles enhance user interaction and align with the overall application design.

**Implement Data Integration**:  
- I will update the component to display the extracted token details.
- I will ensure that each piece of information is clearly labeled and formatted for readability.

**Testing**:  
- I will test the updated `TokenLaunchCard` component locally to ensure that UI improvements function as expected and data is displayed correctly.
- I will conduct cross-browser testing to verify that the enhancements work consistently across different browsers and devices.

**Comment by MSghais** [comment]
Gm! Thank you, everyone.

We prioritized a good description with an ETA (Estimated Time of Arrival)
