### ISSUE TITLE
Staking contract

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#272]
# Description 

Staking contract of ERC20

Follow this nip: https://eips.ethereum.org/EIPS/eip-4626

- [ ] Staking contract
- [ ] Distribute share based on supply available.
- [ ] Can be claim by epoch of 24h and auto compound.
- [ ] Reward is the total supply

**Comment by Iwueseiter** [comment]
Would love to tackle this!
I'm a frontend and smart contract developer. I have a solid background in tailwindCSS, react, nextjs, javascript, typescript, cairo, rust ETC.

**Comment by Supa-mega** [comment]
Can I try solving this issue?

**Comment by No-bodyq** [comment]
Could I try solving this?

**Comment by OWK50GA** [comment]
Can I contribute to this one?

**Comment by suhas-sensei** [comment]
i have worked erc4626 that are implemented in nostra finance protocol for liquid staking. So i think i can take it up.

**Comment by casweeney** [comment]
# I am supper experienced in writing staking contracts logic.

## About me:
I am a software engineer with strong technical skills and expertise in writing complex scalable applications. I have written and tested some advanced Cairo and Solidity smart contracts like building and testing the Synthetix staking contract using Cairo: https://github.com/casweeney/cairo-synthentix-staking

I have contributed to some groundbreaking protocols like Hyperbridge: https://github.com/polytope-labs/hyperbridge/graphs/contributors and my GitHub account has a lot of proof of work.

Leveraging on my skills and experience, I am confident in my ability to tackle new challenges and also solve complex technical issues.


## Tackling this issue
- Given my experience in writing complex staking mechanisms like Synthetix staking protocol, I will write a contract that follows the above description. Check the following multi reward staking implementation in my repo:
https://github.com/casweeney/staking-multiple-reward-tokens

**Comment by Emmanex01** [comment]
Would love to tackle this!

**Comment by mimisavage** [comment]
Can I take this issue?

**Comment by aniruddhaaps** [comment]
ERC-4626 Compatibility
Create a staking contract based on the EIP-4626 standard for tokenized vaults.
Distribute the vault shares proportionate to the ERC20 tokens staked.

Rewards Distribution
Distribute rewards according to the total supply of the staking token, spread over epochs of 24h.
Enable auto-compounding so the rewards are compounded automatically for the stakers.

Epoch-Based Claiming
Allow users to claim their reward at the end of each 24-hour epoch
Accrued rewards to ensure correct distribution per user. Testing:

Tests are written to test staking, reward calculation, epoch claiming, and auto-compounding.
