### ISSUE TITLE
dn 404 contract

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#273]
# Description

DN404 contract.

https://github.com/Vectorized/dn404

# Tasks
Contract needs:

- [ ] To get one nft for X ERC20. This params need to be in storage.

- [ ] URI metadata for NFT creation with different mode, create an enum for it:
-  RandomID (collision can be created, check)
- [ ] Implement test

**Comment by mimisavage** [comment]
Mind if I take this issue?

**Comment by ooochoche** [comment]
I am a smart contract dev, and this is my approach to the tasks

Firstly - i will define storage variables to hold the ERC20 token address and the price for minting one NFT. Then

- create an enum for URI generation modes, including a RandomID option.

- implement logic to generate a random ID, ensuring no collisions by checking existing IDs.

- add a mint function to handle ERC20 transfers, generate metadata, and mint NFTs based on the selected mode.

Lastly - make all required test

**Comment by kfastov** [comment]
May I please work on this?
I have experience in Cairo, particularly with NFTs (ERC721, ERC1155) and migrating contracts from Solidity.
1. I will study the dn404 contract and carefully transfer the logic to Cairo, implementing dn404 factory.
2. I'll add parameters for the NFT creation mode enum (RandomID, maybe adding more variants later) and the conversion ratio between ERC20 and nft tokens
3. I'll implement any integration code needed to integrate this factory into the project
4. I'll write tests for the contract, testing for various paths

**Comment by aniruddhaaps** [comment]
Storage Variables for ERC20 and NFT Parameters in a Contract:

Define storage variables for the ERC20 token address, price in X ERC20 units, and NFT base URI.
Metadata with Modes
Create an enum for metadata generation modes:
RandomID: implement logic to handle collision in case of a clash of IDs.
Implement functions to generate and assign URIs for metadata based on a selected mode.

Purchase of NFT
Implement a function that enables users to mint one NFT for the cost of X ERC20 tokens. Deduct the amount and transfer to the contract or the wallet in question.

Testing:
Write comprehensive tests to ensure the correct functionality of NFT minting, ERC20 payments, and URI creation, including collision handling of RandomID.
