### ISSUE TITLE
Test and Fix build Android & IOS

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#275]
# Description

Test Mobile version and fix build

- [ ] Test and fix the build of apps/mobile in Android & IOS.
- [ ] Do screenshot of the Android version working and IOS version working
- [ ] Test features in the different OS mobile version
- [ ] Verify and check
- [ ] Prepare config for deploy with expo and in platform like IOS and Android
- [ ] Add manifest and config for native package

**Comment by jedstroke** [comment]
Let me take on this one!

**Comment by Amarjeet325** [comment]
I'd be happy to do this.

**Comment by mimisavage** [comment]
Can I work on this, please?

**Comment by aniruddhaaps** [comment]
First I will test the mobile build on Android and iOS devices/emulators to identify any platform-specific issues.
Fix build errors, verify key features, and ensure compatibility on both platforms.
Prepare deployment configurations using Expo, including manifests and native package settings for iOS and Android.
Provide screenshots of working Android and iOS versions.

**Comment by Supa-mega** [comment]
I’d like to resolve this.

**Comment by caxtonacollins** [comment]
Could I try solving this?

**Comment by 7-falseparfait** [comment]
Please, I would love to work on this.

**Comment by ncoquelet** [comment]
Could I grab this task?
