### ISSUE TITLE
Nameservice Fullstack integration

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#279]
# Description 

We have a nameservice.cairo to test, deployed to Sepolia soon.
We need a Nameservice like Starknet.id or .brother.

Create components and screens in the mobile to buy one nameservice, render nameservices claimed card.

Indexer and endpoints need to be done. We can split the tasks in frontend and backend/indexer issues.

Example:
https://id.supbro.fun/identities

https://app.starknet.id

ENS

apps/mobile:

- [ ] Create components and screens
- [ ] Component to buy a name (verify the name, check amount)
- [ ] List all name bought, with expiry time and owner

apps/indexer
- [ ] Create the Indexer scripts

apps/backend
- [ ] Create the backend endpoints for nameservice.cairo events

**Comment by suhas-sensei** [comment]
I’d like to work on this. I propose creating mobile components for name purchasing, indexer scripts for efficient data retrieval, and backend endpoints to handle nameservice.cairo events. This approach ensures seamless integration across all layers.

Draft pr in 24hrs

also a doubt  if the backend also handles validations for name availability or is managed solely on the frontend but guess ill figure it out.

**Comment by aniruddhaaps** [comment]
For the front-end (Apps/Mobile)
Create name buying and management components and screens. A "Buy Name" flow to check availability and process payments.

For the back-end (Apps/Backend)
Implement the back-end endpoints needed to process nameservice.cairo events. Create an endpoint for name validation, purchase, and ownership queries.
Indexer (Apps/Indexer)
Create indexer scripts to track events on Sepolia and index the nameservice.cairo data efficiently.

**Comment by Supa-mega** [comment]
Mind if I take this issue?

**Comment by ooochoche** [comment]
I have gone through the description, and I can resolve all task

**Comment by ncoquelet** [comment]
I'm a senior fullstack dev, assign me some of your tasks and I'm committed to finishing them by the end of the next few weeks.

**Comment by MSghais** [comment]
> I’d like to work on this. I propose creating mobile components for name purchasing, indexer scripts for efficient data retrieval, and backend endpoints to handle nameservice.cairo events. This approach ensures seamless integration across all layers.
> 
> Draft pr in 24hrs
> 
> also a doubt if the backend also handles validations for name availability or is managed solely on the frontend but guess ill figure it out.

gm, can you ping me on TG please?

**Comment by Jagadeeshftw** [comment]
Hi, I’d like to work on this issue as I have experience in front-end development.
I can implement the required changes and ensure everything works seamlessly as described.
I estimate completing the work within 12-24 hours. Could you please assign this to me?

**Comment by bruhhgnik** [comment]
### Application for Nameservice Feature Development

Hi, 

I’d like to contribute to this project. I have experience in frontend and backend development, as well as working with blockchain-specific functionalities. Here's how I propose splitting the tasks:

1. **Frontend (apps/mobile):**
   - Create screens and components for buying and managing names.
   - Implement features like name verification, amount checking, and listing purchased names with expiry and ownership details.

2. **Indexer (apps/indexer):**
   - Write indexer scripts to process nameservice.cairo events efficiently.

3. **Backend (apps/backend):**
   - Build endpoints to support the frontend and indexer with real-time data.

I am comfortable working on either frontend or backend/indexer tasks based on project needs.

Thank you!

**Comment by NueloSE** [comment]
I’d like to resolve this issue kindly assign me.

**Comment by Rayguti** [comment]
Why I’m Interested: With experience in building mobile components and working with backend integrations, this issue aligns perfectly with my skills. It offers an opportunity to contribute to a decentralized identity system, enhancing the mobile app's functionality and ensuring a seamless experience for users. I'm excited to work on such a key feature for the platform and explore how decentralized services are integrated with mobile applications.

Proposed Approach:

    Mobile App Development:
        Create Components & Screens:
            Build a user-friendly interface to allow users to buy and manage names.
            Add a component to verify the name availability, check the amount needed, and confirm the purchase.
            Implement a listing screen to display all names bought, showing details such as expiry time and ownership.
        UI/UX Considerations:
            Ensure smooth and intuitive navigation for purchasing and managing names.
            Handle edge cases like expired names, unavailable names, or failed transactions.

    Backend Development:
        Create Endpoints for nameservice.cairo Events:
            Set up backend endpoints to listen to events from nameservice.cairo, handling claims, purchases, and name expiration.
            Ensure secure and accurate event processing and update the database with relevant name data.
        API Integration:
            Provide API endpoints to fetch names and associated details (e.g., expiry time, owner).

    Indexer Development:
        Create Indexer Scripts:
            Develop indexer scripts to collect and store name-related data from the blockchain events triggered by nameservice.cairo.
            Ensure the indexer handles name claims, purchases, and expirations correctly, storing all relevant data in a structured format for efficient querying.

    Testing and Validation:
        Ensure proper testing of:
            The mobile app’s functionality (name verification, buying, listing).
            Backend processing of events and storing/updating name-related data.
            Indexer scripts for data accuracy and efficiency.

    Adhere to Guidelines:
        Follow the contributor’s guide for style, structure, and best practices to ensure consistency with the project.

Outcome: The mobile app will be fully equipped with a NameService feature, allowing users to purchase and manage names. The backend will process events from nameservice.cairo, and the indexer will efficiently store and query name-related data. This will provide users with a seamless and decentralized identity service integrated within the app.

**Comment by akintewe** [comment]
Can I take care of this issue?

My ETA is 50 hours

**Comment by Dhir0808** [comment]
May I take care of this?

Frontend (Mobile):
Create screens/components to buy a name (validate, check cost) and list claimed names (expiry, owner).
Indexer:
Scripts to process nameservice.cairo events.
Backend:
Endpoints for name ownership and expiry data.

**Comment by DotworldX** [comment]
I’d like to resolve this.

**Comment by CEOliam** [comment]
I'd like to take this issue.

**Comment by mimisavage** [comment]
Could I grab this task?
