### ISSUE TITLE
Pump details screen

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#28]
Improve the UI of the LaunchDetail screen. 
Related to #27 

This issue can be split into 2: improve the overall UI already existing, add others UI components.

Screen: LaunchDetail

Component: TokenLaunchDetail

Can be saw when you click on details in the pump card.

- [ ]  Styles basics.

- [ ] Add tabs for TX, Holders etc, hooks not finished. Use the component:
TabSelector and create a tabs for it. Don't change the screens.
- [] Create others screens

![image](https://github.com/user-attachments/assets/267dd9d2-81ea-40bf-8c34-01c474d60a3e)

**Comment by Iwueseiter** [comment]
Hi

**Comment by ikemHood** [comment]
can i take on this @MSghais

**Comment by ShantelPeters** [comment]
Can I work on this @MSghais

**Comment by Immanuelolivia1** [comment]
@MSghais can I be assigned this issue I have been actively contributing to artpeace repo and I believe I will do justice to this issue

**Comment by ScottyDavies** [comment]
Hello @MSghais,
I will like to take up this issue

**Comment by lauchaves** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hey! I'm Lau Chaves, and I would like to contribute to this issue!


I have over 5 years of experience working with JavaScript, React, and TypeScript, ruby... Im also part of Dojo Coding Costa Rica!

My primary role has been as a front-end developer, and I have a keen eye for detail and a strong focus on mobile-first approaches. I ensure the quality of my work through rigorous self- QA processes. I have a solid knowledge of CSS, Sass, and styled-components.

Feel free to check my onlydust profile here and github profile: lauchaves!


### How I plan on tackling this issue
For this issue, my approach would be:

- Check Current UI: Look at how LaunchDetail and TokenLaunchDetail are set up now.
- Add Tabs: Use the TabSelector component to add tabs for TX, Holders, etc. This will help organize the info better, ill finish any pending hook!
- Create/Update Screens: create or update the screens for each tab (TX and Holders).
Style it Up: Update the styles to make everything look good and match the app’s design.
- Test: Make sure the tabs work and the new screens look right.

**Comment by Supa-mega** [comment]
hi @MSghais i'll be thrilled to work on this project if assigned the task

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have 2 years of experience as a front-end developer, with expertise in JavaScript, React.js, CSS, and HTML. I've built full-stack projects like Crypto Bank, handling both front-end and back-end development. My skills in creating responsive, dynamic interfaces make me well-equipped to contribute effectively to your project.

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a web developer with over 6 years experience building applications both personal and professional projects. I started contributing to open source via onlydust in march this year and I have contributed to a couple of issues, you can see them in my profile.

### How I plan on tackling this issue
Improve the UI of the LaunchDetail screen by using the TokenLaunchDetail component, I will hadd tabs for the TX, Holders and other parts

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet community🇷.

### How I plan on tackling this issue
Here's how I would approach the problem of improving the UI for the LaunchDetail screen and the Pump card screen, based on the current state shown in the screenshots:

1. Improving the Overall UI of the LaunchDetail Screen:
Component: TokenLaunchDetail

Styles Basics:
Spacing and Alignment: Improve spacing between elements (e.g., coin address, owner, etc.) for better readability. Ensure consistent padding and margins across all elements.
Typography: Use a more readable and consistent font size and weight for titles, descriptions, and other text elements. Consider highlighting important details like the coin address and owner with a slightly bolder font.
Colors: Adjust the color scheme to increase contrast between text and background, especially for addresses and labels. Consider using a different color for clickable elements like the "Buy" and "Sell" buttons.
Button Styling: Enhance the "Buy" and "Sell" buttons with more modern styling—rounded corners, slight shadows, or gradients. Make them more visually appealing and distinguishable.
Adding Tabs:

Tabs for TX, Holders, etc.:
Use the existing TabSelector component to create tabs for different sections like TX, Holders, Overview, etc.
Ensure smooth transitions between tabs without reloading the screen.
Improve the UI for tab content display, making sure each tab content area is well-structured and organized.
Hooks: Make sure the hooks related to data fetching for these tabs are optimized and loading states are handled well.
Future Screens:

Plan and design additional screens to enhance the functionality and user experience. For instance, a detailed view of Holders or a graph showing the token's performance could be valuable additions.
2. Improving the UI of the Pump Card Screen:
Component: TokenLaunchCard
Simplify and Enhance:
Card Layout: Simplify the card layout by clearly separating sections for different pieces of information (e.g., token details, action buttons).
Interactive Elements: Ensure buttons like "Buy" and "Sell" are prominently displayed and clearly labeled. They should have hover effects to indicate interactivity.
Responsive Design: Ensure the card design is responsive and looks good on different screen sizes.
Visual Enhancements: Consider adding subtle animations to elements on the card, such as a slight bounce effect on button click or a fade-in effect for content.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged

Hi @MSghais 
I'm interested in tackling the issue of improving the UI of the Pump card screen, specifically focusing on the TokenLaunchCard component. This is my first contribution to this project, but I bring 3 years of experience with frontend technologies, including Next.js, TypeScript, and Tailwind CSS. My background includes working on UI improvements for various projects like Opscan and the Blink extension.

### How I plan on tackling this issue
### Review and Refine UI Design

**Current State**: The Pump card screen displays details such as Coin Address, Owner, Supply, Price, and other token information.  
**Objective**: I will improve the visual presentation and usability of the `TokenLaunchCard` component based on the provided data.

### Simplify the UI

**Visual Improvements**:  
- I will use Tailwind CSS to update styles for better readability and visual appeal.
- I will ensure consistent spacing, alignment, and color schemes.

**Data Presentation**:  
- I will enhance the display of token details, making key information like Coin Address, Owner, Supply, Price, and Threshold Liquidity clearly visible and easy to understand.

### Integrate Extracted Data

**Content Integration**:  
- **Coin Address**: I will display this prominently.
- **Owner**: I will clearly indicate the token owner.
- **Supply, Price, Threshold Liquidity**: I will present these values in a structured format.
- **Quote Token and Step Increase**: I will ensure these details are included and easily accessible.
- **Token and Buy/Sell Actions**: I will provide buttons for actions like creating tokens and buying/selling, clearly labeled and functional.

### Technical Steps

**Update Styles**:  
- I will refactor the `TokenLaunchCard` component using Tailwind CSS to apply modern, responsive design principles.
- I will ensure the updated styles enhance user interaction and align with the overall application design.

**Implement Data Integration**:  
- I will update the component to display the extracted token details.
- I will ensure that each piece of information is clearly labeled and formatted for readability.

**Testing**:  
- I will test the updated `TokenLaunchCard` component locally to ensure that UI improvements function as expected and data is displayed correctly.
- I will conduct cross-browser testing to verify that the enhancements work consistently across different browsers and devices.
