### ISSUE TITLE
Settings screen

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#29]
Improve UI of the Profile screen and components for Desktop and Mobile:

Screen: Settings

Components: 

- Private Key Import
- Relays config

- []  UI styles in Desktop and Mobile for the screens
- [] UI improvement of all components
- [] Create a component for Toggle theme

Desktop: 
![image](https://github.com/user-attachments/assets/ba819689-1f60-437c-a54e-5db7006db60d)

Mobile:
![image](https://github.com/user-attachments/assets/9d8aa422-4f5b-4a46-af63-902f99212afc)

**Comment by ikemHood** [comment]
hi

**Comment by od-hunter** [comment]
H

**Comment by Calebux** [comment]
@MSghais can i take this up?

**Comment by martinvibes** [comment]
hello @MSghais i would love to work on this

**Comment by lauchaves** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hey! I'm Lau Chaves, and I would like to contribute to this issue!

I have over 5 years of experience working with JavaScript, React, and TypeScript, ruby... Im also part of Dojo Coding Costa Rica!

My primary role has been as a front-end developer, and I have a keen eye for detail and a strong focus on mobile-first approaches. I ensure the quality of my work through rigorous self- QA processes. I have a solid knowledge of CSS, Sass, and styled-components.

Feel free to check my onlydust profile here and github profile: lauchaves!


### How I plan on tackling this issue
For this one, my approach would be:

- Review Existing UI: Assess current designs to identify improvement areas for desktop and mobile.
- Design Improvements:
- Private Key Import: Enhance visual presentation and user experience.
- Relays Config: Improve layout and styling for clarity and usability.
- Toggle Theme Component: Create a user-friendly theme switcher.
- Responsive Design: Ensure all UI elements are styled for both desktop and mobile, maintaining consistency across screen sizes!
- UI Consistency: Apply a cohesive style guide for visual harmony.
Testing and QA: Test across devices and screen sizes to ensure functionality and appeal.

**Comment by Supa-mega** [comment]
hi @MSghais can i hop on this ?

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have 2 years of experience as a front-end developer, with expertise in JavaScript, React.js, CSS, and HTML. I've built full-stack projects like Crypto Bank, handling both front-end and back-end development. My skills in creating responsive, dynamic interfaces make me well-equipped to contribute effectively to your project.

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a web developer with over 6 years experience building applications both personal and professional projects. I started contributing to open source via onlydust in march this year and I have contributed to a couple of issues, you can see them in my profile.

### How I plan on tackling this issue
Modifying the settings page UI to make it look better than what it looks like currenty and making sure its mobile responsive

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged

Hi @MSghais 

I'm available to work on improving the UI of the Profile screen and related components for the Settings screen (#29). I’m Benjamin, with 3 years of experience in Next.js, TypeScript, and frontend development. My background includes contributing to various projects on OnlyDust and tackling complex UI issues.

### How I plan on tackling this issue
### UI Improvements
- **Revamp Design**: I will redesign the Settings screen for both desktop and mobile, ensuring it is consistent, responsive, and user-friendly across different devices.

### Component Enhancements
- **Private Key Import**: I will improve the UI and functionality for importing private keys, making it intuitive and secure.
- **Relays Config**: I’ll enhance the UI for configuring relays, displaying existing relays and allowing users to set up new ones.

### New Component Creation
- **Toggle Theme**: I’ll add a component that allows users to switch themes, ensuring the toggle is easily accessible and integrates well with the existing UI.

### Testing and Validation
- **Local Testing**: I’ll test the UI changes on both desktop and mobile to ensure they function as intended.
- **Responsive Design**: I will verify that all UI improvements work seamlessly across different screen sizes and devices.
- **User Experience**: I’ll ensure that the Private Key Import, Relays Config, and Toggle Theme components are intuitive and enhance the overall user experience.

**Comment by bhavyagosai** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hey, I am Bhavya, a seasoned frontend engineer with two years of professional experience. I have been working with react, react native, nextjs, typescript, shadcn, tailwindcss for a while now and am familiar with  the code. Have worked previously on the joyboy app too!

### How I plan on tackling this issue
to improve the settings/profile screen:
- first I will see the overall ui of the app/website and improve according to that.
- add margins/paddings to make this look good

Individual pointers for improvements:
- The title “Settings” and the back arrow could be more distinct. Consider increasing the size of the title slightly and aligning the back arrow more effectively (perhaps vertically centered with the title).
- Add more consistent spacing between sections. For example, the space between the "Switch theme" section, the password input, and the relay information can be standardized to improve readability.
- Ensure all elements are perfectly aligned (including buttons, icons, and input fields). 
- Password label can be "Enter Password" making it more descriptive.
- buttons themselves can be a little bit smaller or in accordance with the text size being used and icons and texts can be aligned properly.
- The "Switch theme" button could be enhanced with a more interactive switch toggle design, which would be more intuitive than a simple button. A toggle switch with clear light/dark mode icons would be visually appealing and provide immediate feedback.
- The relays section in mobile view seems slightly cramped, we can maybe add collapsible or accordions there
- can use subtle divider lines between sections.
- sidebar can have aligned and spaced text with icons.
- can add small animations/transitions to make/feel the ui smooth

**Comment by DanielEmmanuel1** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hello, my name is Daniel and I am a frontend web3 developer with experience in building scalable and really clean UI

### How I plan on tackling this issue
Firstly, I would sketch out wireframes UI to see how I want the new UI to be
I would also want to know if u will be sticking to the major colors scheme you currently have or if it open to suggestion
Make a quick UI design on Figma utilizing design patterns that aids both scalability user experience

Go through each component files and update the codebase based on the new designs structures
Writing clean and concise code, I will create a beautiful UI hence further better user experience.

If given the chance this will make it my second contribution to OD hack and am very confident in my abilities to deliver on this
