### ISSUE TITLE
Indexer Launchapd to update

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#295]
# Description

apps/indexer:

In the buy and sell token, we need to upgrade the launch model and directly call a Postgres UPDATE query if possible:

- [ ] Create a query to update the token_launch model after each sell/buy:
threshold liquidity
available_supply
liquidity_raised
total_token_holded

**Comment by emarc99** [comment]
Could I take a shot at this?

**Comment by EjembiEmmanuel** [comment]
Let me handle this issue!

**Comment by MrRoudyk** [comment]
I'd love to work on this!

**Comment by estherbreath** [comment]
I would like an opportunity to contribute to this project.
Could you assign this issue to me, please?

**Comment by CEOliam** [comment]
I'd be happy to do this.

**Comment by vestor-dev** [comment]
I'd love to work on this!
kindly assign

**Comment by Supa-mega** [comment]
Could I take a shot at this? first time contributor

**Comment by aniruddhaaps** [comment]
Alternatively, you can directly update this token_launch model with a Postgres UPDATE query to resolve the issue. The query would then look something like this:

UPDATE token_launch
SET threshold_liquidity = $1, 
    available_supply = $2, 
    liquidity_raised = $3, 
    total_token_held = $4
WHERE token_id = $5;

Pass the necessary values dynamically from the transaction logic to ensure that the updates are in sync with every buy/sell operation. This is less overhead compared to an update-driven ORM-based.

**Comment by Unickhub** [comment]
Could I take a shot at this?
