### ISSUE TITLE
Add NIP-07 Extension 

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#3]
Add the possibility of using the extension with a NIP-7

TODO:

- [ ] Auth Screen & Login: Create maybe another one
- [ ] check if the window.nostr is enabled and we don't have a private key
- [ ]  Hooks change to made:
for sendNote, reaction, follow etc for mainly write access

**Comment by od-hunter** [comment]
Hello @MSghais , is this open for contribution? If yes can I be assigned please?

**Comment by MartinXV111** [comment]
I think the NIP-07 extension has already been added yeah? :)
