### ISSUE TITLE
Nostr: Repost hook

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#30]
Implement the hook to repost note in the Nostr, do it in the packages/afk_nostr_sdk and add it to the mobile Post component

- [ ] Create useRepost hook in the packages/afk_nostr_sdk
- [ ] Add it to the mobile PostCard when you click on the icon

NIP implementation: https://github.com/nostr-protocol/nips/blob/master/18.md

Create the hook in the packages/afk_nostr_sdk and call it here in the onPress:

![image](https://github.com/user-attachments/assets/5a6aa70b-5f75-4a6a-8187-27447971eb57)

**Comment by Jemiiah** [comment]
B

**Comment by petersdt** [comment]
can i

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
s

**Comment by ShantelPeters** [comment]
Can i work on this @MSghais

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged

Hi @MSghais 

I want to tackle the implementation of the repost hook for Nostr (#30). My name is Benjamin, and I have 3 years of experience working with Next.js, TypeScript, and frontend development. I’ve previously contributed to projects on OnlyDust and am familiar with creating and integrating hooks effectively.

### How I plan on tackling this issue
## Task
The task is to create a `useRepost` hook within the `packages/afk_nostr_sdk` and integrate it into the mobile `PostCard` component. This involves implementing the hook to handle reposting notes and updating the UI accordingly.

### Create `useRepost` Hook
- **Implementation**: I will implement the `useRepost` hook in `packages/afk_nostr_sdk`. This hook will handle the logic for reposting a note on Nostr.

### Integrate Hook into `PostCard`
- **Functionality**: I’ll add functionality to the mobile `PostCard` component. I will update the `onPress` event to use the `useRepost` hook when the repost icon is clicked.

## Testing and Validation

- **Local Testing**: I’ll verify that the `useRepost` hook works as expected by testing it locally, ensuring it correctly reposts notes and handles any potential errors.
- **UI Integration**: I’ll test the integration within the `PostCard` component to ensure the repost functionality is responsive and user-friendly.

**Comment by Benjtalkshow** [comment]
> > I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).
> > ### My background and how it can be leveraged
> > Hi @MSghais
> > I want to tackle the implementation of the repost hook for Nostr (#30). My name is Benjamin, and I have 3 years of experience working with Next.js, TypeScript, and frontend development. I’ve previously contributed to projects on OnlyDust and am familiar with creating and integrating hooks effectively.
> > ### How I plan on tackling this issue
> > ## Task
> > The task is to create a `useRepost` hook within the `packages/afk_nostr_sdk` and integrate it into the mobile `PostCard` component. This involves implementing the hook to handle reposting notes and updating the UI accordingly.
> > ### Create `useRepost` Hook
> > 
> > * **Implementation**: I will implement the `useRepost` hook in `packages/afk_nostr_sdk`. This hook will handle the logic for reposting a note on Nostr.
> > 
> > ### Integrate Hook into `PostCard`
> > 
> > * **Functionality**: I’ll add functionality to the mobile `PostCard` component. I will update the `onPress` event to use the `useRepost` hook when the repost icon is clicked.
> > 
> > ## Testing and Validation
> > 
> > * **Local Testing**: I’ll verify that the `useRepost` hook works as expected by testing it locally, ensuring it correctly reposts notes and handles any potential errors.
> > * **UI Integration**: I’ll test the integration within the `PostCard` component to ensure the repost functionality is responsive and user-friendly.
> 
> @Benjtalkshow, can you ping me in Telegram please? My handle is @MSG_Encrypted.
> 
> Also please can you send me your ETA for this issue? Very important

Ok @MSghais
