### ISSUE TITLE
Nostr hook bookmark 

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#31]
Implement the hook to bookmark in Nostr.

NIP 51 implementation for Bookmark/List: https://github.com/nostr-protocol/nips/blob/master/51.md

Do it in the package and add it to the mobile Post component

- [ ] Create hooks in the packages/afk_nostr_sdk: See the NIP implementations to check what hooks need to be done.
- [ ] Add it to the mobile PostCard when you click on the icon

Create the hook in the packages/afk_nostr_sdk and call it here in the onPress:

![image](https://github.com/user-attachments/assets/5a6aa70b-5f75-4a6a-8187-27447971eb57)

**Comment by martinvibes** [comment]
i

**Comment by petersdt** [comment]
W

**Comment by Jemiiah** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
i would love to work on this issue

**Comment by ShantelPeters** [comment]
@MSghais please can I be assigned to this

**Comment by GoSTEAN** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
 I have a very background in web development, Solidity smart contracts, and React, with experience in backend development, including user authentication and database management. This diverse skill set can be leveraged to create efficient, secure, and scalable web3 applications, integrating blockchain technology with user-friendly interfaces.

### How I plan on tackling this issue
To implement the hook for bookmarking in Nostr and create the `useRepost` hook in the package and add it to the mobile `PostCard` component, you can follow these five steps:

### Step 1: **Define the Bookmark Hook**
- **Objective**: Create a custom hook to handle bookmarking logic in the `afk_nostr_sdk` package.
- **Action**: Identify the functionality needed for bookmarking, such as saving a post to a user's favorites or marking it for later. Define the API calls and state management required for this functionality.

### Step 2: **Integrate Bookmark Hook into Mobile Post Component**
- **Objective**: Implement the hook into the mobile `Post` component where users can bookmark posts.
- **Action**: Add the hook to the component and trigger it when a user interacts with the bookmark icon. Ensure that the UI updates to reflect the bookmarked status.

### Step 3: **Define the Repost Hook**
- **Objective**: Create a `useRepost` hook that will handle the reposting logic in the `afk_nostr_sdk` package.
- **Action**: Identify the necessary logic for reposting, including any API calls, state management, and UI updates. Define the hook to manage this functionality.

### Step 4: **Integrate Repost Hook into PostCard Component**
- **Objective**: Add the `useRepost` hook to the `PostCard` component, allowing users to repost content with a simple interaction.
- **Action**: Integrate the hook into the `onPress` function of the repost icon in the `PostCard` component. Ensure that the hook triggers the repost action and updates the UI accordingly.

### Step 5: **Test and Optimize**
- **Objective**: Ensure the new hooks work seamlessly in the components.
- **Action**: Test the hooks in the respective components to confirm they function as expected. Debug and optimize as necessary, ensuring a smooth user experience.

**Comment by MSghais** [comment]
@Jemiiah, can you ping me on Telegram please, my handle is MSG_Encrypted.
Also, please send me an ETA for this issue.

**Comment by Jemiiah** [comment]
@MSghais sure would do that ser

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hi @MSghais,

I would like to work on the implementation of the bookmark hook for Nostr (#31). My name is Benjamin, and I have 3 years of experience working with Next.js, TypeScript, and frontend development. I’ve contributed to projects on OnlyDust and am experienced in creating and integrating hooks effectively.

### How I plan on tackling this issue
The task is to create a useBookmark hook within the `packages/afk_nostr_sdk` and integrate it into the mobile PostCard component. This involves implementing the hook to handle bookmarking notes and updating the UI accordingly.

## Create useBookmark Hook
- Implementation: I will implement the useBookmark hook in packages/afk_nostr_sdk. This hook will handle the logic for bookmarking a note on Nostr according to NIP-51.

## Integrate Hook into PostCard
- Functionality: I’ll add the functionality to the mobile PostCard component, updating the onPress event to use the useBookmark hook when the bookmark icon is clicked.

## Testing and Validation
- Local Testing: I’ll verify that the useBookmark hook works as expected by testing it locally, ensuring it correctly bookmarks notes and handles any potential errors.
- UI Integration: I’ll test the integration within the PostCard component to ensure the bookmark functionality is responsive and user-friendly.
