### ISSUE TITLE
Argent Telegram app in PWA and Fix application error related to Telegram

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#311]
# Description

We have started a Telegram integration with a mini-app on Telegram.
Now we want to continue the Argent Telegram SDK integration in the apps/pwa to enable easy wallet in the Telegram environment.

We have a application error related to the Telegram app.

Docs here: https://docs.argent.xyz/argent-wallets/telegram-wallet/setup-guide

You need to create a Telegram Argent account with the Argent bot in Dev telegram mode.

- [ ] Fix application error of Telegram
- [ ] Start connect a Telegram account if we are connected and using telegram (web.Telegram is enabled normally)
- [ ] Add session of place_pixel for Telegram
- [ ] Call a data with Telegram account

**Comment by MSghais** [comment]
> Can I attempt this issue, am a frontend developer and would love to work on this issue

Gm, ping me on Telegram please.
Also do you have an ETA?

**Comment by lindsaymoralesb** [comment]
Is this issue still available?

**Comment by lindsaymoralesb** [comment]
Hello! Lindsay Morales - Software Engineer with almost 5 years of exp. Multiple contributions to this project already.
I'd like to work on this issue. This is what I would do:
1. Check the setup guide docs
2. Debug the issue
3. Apply fixes

ETA: 2-3 days
