### ISSUE TITLE
Indexer launchpad: Add Share by user model

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#324]
# Description

Add change to the indexer NestJS repo coming soon:

- [ ] Create Share by user model (check launchpad_types.cairo for the model representation)
- [ ] Create this model that represent a share for one user at one contract when first tx buy occurs
- [ ] Update model data at each buy/sell tx

**Comment by ooochoche** [comment]
@MSghais can I work on this?

**Comment by EjembiEmmanuel** [comment]
@MSghais, please kindly assign as discussed.

**Comment by mimisavage** [comment]
Can I be assigned to this ?

**Comment by GradleD** [comment]
I’d like to help with this.

**Comment by EjembiEmmanuel** [comment]
I'd like to take this issue.
