### ISSUE TITLE
Launchpad: Verify formula Bonding Curve for Linear

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#329]
# Description

We have two bonding curve type with different formula.

- One Linear bonding curve formula (by default, starting with it, exponential finish soon).

- [ ] Test Linear bonding curve outside launchpad. Just the utils
- [ ] Test linear bonding curve with Launchpad token and check share_user.amount_owned

**Comment by kfastov** [comment]
Can I take this one?

ETA 1 day

**Comment by manlikeHB** [comment]
Can I work on this? 

ETA 1 day
