### ISSUE TITLE
Launchpad: Exponential Bonding curve

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#330]
# Description

Exponential Bonding curve localted in exponential.cairo

- [ ]  Test Exponential bonding curve outside launchpad

- [ ]  Test Exponential bonding curve in the launchpad and check share_user.amount_owned etc

**Comment by casweeney** [comment]
I can work on this @MSghais.

### Tackling this issue:
- I will first study the existing launchpad codebase to get a grasp of the implementation.
- I will write test cases for the above listed points and ensure that all cases are properly accounted for.

## ETA: 2 - 3 days tops

**Comment by JoE11-y** [comment]
Can I work on this.
ETA: 1 day
