### ISSUE TITLE
PWA fixes for Session and Telegram

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#331]
# Description 

apps/pwa to fixe Session, login and add Telegram support for pixel art.

1. Fix session argent in Pixel packages and Pwa when you connect to account to do have to click every time when placing a pixel.

2. Continue telegram integration of Pixel pwa: add session:
. https://docs.argent.xyz/argent-wallets/telegram-wallet

**Comment by sajalbnl** [comment]
May I pick this up?

**Comment by MSghais** [comment]
Ping me on Telegram

> May I pick this up?

**Comment by ooochoche** [comment]
Gm, can I be assigned this issue?

**Comment by michojekunle** [comment]
Hello Please Can I try solving this issue?

**Comment by addegbenga** [comment]
I will love to work on this.
ETA 48hrs

**Comment by pheobeayo** [comment]
Could I take on this issue?

**Comment by starknetbrother** [comment]
Can I tackle this one?

**Comment by lauchaves** [comment]
Hey! I'm Lau Chaves, I have been contributing to this project and would like to keep doing so I would like to contribute to this issue!

I have over 5 years of experience with JavaScript, ReactJS,React Native TypeScript, and Ruby. I’m now enthusiastic about web3 and eager to learn more! I’m also a member of Dojo Coding Costa Rica. 

For this one I’d check the current session implementation, and Id prepare a fix so the session works automatically after logging in, so users don’t have to click every time. I’d also finish the Telegram integration following the steps on the link that's on the issue description

**Comment by caxtonacollins** [comment]
Can I take care of this issue?

**Comment by Jagadeeshftw** [comment]
Hi,
I’d love to work on this issue as I have strong experience with front-end development. Please assign this to me, and I’ll deliver an efficient and secure PR within 12-24 hours.

**Comment by 1nonlypiece** [comment]
Hi ,
I’d like to work on this issue as I have experience in building frontend interfaces using frameworks like React and Next.js.


ETA:
 I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by akintewe** [comment]
I’m interested in this one.

**Comment by Amarjeet325** [comment]
Can I take this issue?

**Comment by addegbenga** [comment]
I will love to work on this
ETA 24hrs
