### ISSUE TITLE
Cairo contract to mint aBTC

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#34]
Cairo contract to mint aBTC with a one-to-one mint with wBTC.

Create the mintVaultBTC and one contract for a reserve of wBTC in one contract. 

- [] Architecture
- [] ERC20 Mintable with AccessControl from OpenZeppelin
- [] Deposit function
- [] Withdraw function

Bonus: Upgradeable contract

**Comment by ikemHood** [comment]
h

**Comment by Jemiiah** [comment]
S

**Comment by Gift-Naomi** [comment]
Hi

**Comment by martinvibes** [comment]
i

**Comment by estherbreath** [comment]
@MSghais I am a Smart contract developer in Solidity and Cairo. I would like to work on this issue.

Harnessing my expertise in Solidity and Cairo, I will tackle this issue by crafting two pivotal smart contracts:
    1. MintVaultBTC: Orchestrates the minting of aBTC tokens, aligning with wBTC reserves for a seamless one-to-one exchange. 
    2. ReserveContract: Acts as the custodian for wBTC, managing deposits and withdrawals to fuel the minting process. 
I will ensure these contracts communicate flawlessly, with the ReserveContract verifying wBTC availability before minting proceeds. Leverage Cairo's strengths for enhanced efficiency and security, crucial for financial applications.
After rigorous testing, I would deploy these contracts to a suitable environment, optimizing for both performance and cost.

**Comment by MSghais** [comment]
> I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).
> ### My background and how it can be leveraged
> 
> @MSghais I am a Smart contract developer in Solidity and Cairo. I would like to work on this issue. I have also worked on similar issues on onlydust
> ### How I plan on tackling this issue
> 
> Harnessing my expertise in Solidity and Cairo, I will tackle this issue by crafting two pivotal smart contracts: 1. MintVaultBTC: Orchestrates the minting of aBTC tokens, aligning with wBTC reserves for a seamless one-to-one exchange. 2. ReserveContract: Acts as the custodian for wBTC, managing deposits and optimizing for both performance and cost.

GM @estherbreath! Can you ping me on Telegram and join the AFK group, please?
My handle is MSG_Encrypted

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am  blockchain developer with years of experience

### How I plan on tackling this issue
I would approach this issue with following steps
1  I would design a modular architecture: 
Separating the MintVaultBTC and wBTCReserve contracts to manage the one-to-one mint relationship between aBTC and wBTC.
2  Implement ERC20 Mintable with AccessControl:
 Use OpenZeppelin's ERC20Mintable and AccessControl contracts to create the aBTC token and manage permissions.
3  Develop Deposit and Withdraw functions: 
In the wBTCReserve contract, implement functions to allow users to deposit and withdraw their wBTC.
4  Implement Minting Process: 
In the MintVaultBTC contract, create a function to mint aBTC tokens based on the deposited wBTC.
5  Make the contract Upgradeable (Bonus): 
Utilize OpenZeppelin's Upgrades Plugins to enable future contract upgrades without disrupting functionality.
6  Thoroughly test and deploy: 
Ensure the contracts are well-tested and prepare the necessary deployment scripts.

**Comment by manlikeHB** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hi, I am a Cairo dev with experience developing smart contracts.

### How I plan on tackling this issue
- I would create the mintVaultBTC contract which would hold the wBTC and manage minting and burning of aBTC.
- I would create the ERC20 mintable token representing aBTC
- I will use OpenZeppelin’s AccessControl and Upgradeable contract to manage roles for minting, burning, managing the vault and make contract upgradable.
- I will write a comprehensive test to ensure deposit, withdraw, mint, and burn functions work as expected and test the interactions between MintVaultBTC and aBTCToken.

**Comment by MPSxDev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a Cairo enthusiast and part of DojoCoding. I have participated in Starknet Bootcamp.

### How I plan on tackling this issue
### 1. Architecture Design
- Outline the system architecture including `mintVaultBTC` and the wBTC reserve contract.
- Ensure clear interaction flows between minting and reserve management.

### 2. ERC20 Mintable Contract
- Utilize OpenZeppelin's ERC20 Mintable with AccessControl.
- Implement minting logic for aBTC based on one-to-one wBTC deposits.

### 3. Deposit Function
- Create a function to deposit wBTC into the vault.
- Trigger minting of equivalent aBTC upon successful deposit.

### 4. Withdraw Function
- Implement a function to withdraw wBTC, burning the corresponding aBTC.

### 5. Bonus: Upgradeable Contract
- Consider using OpenZeppelin’s upgradeable proxy pattern to allow future upgrades without redeploying the entire contract.

### 6. Testing and Security
- Perform thorough testing for minting, deposit, and withdrawal functionalities.
- Ensure the contract is secure against common vulnerabilities.

---

I look forward to being assigned to this issue and am available to start working immediately. I'm committed to achieving the desired outcome, even beyond the hackathon.
