### ISSUE TITLE
Locker change List Alexandria to Vec Starknet storage

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#341]
# Description

We have a locker_position.cairo and locker_manager.cairo same as Unruggable.
We need to upgrade the List of Alexandria storage to the Vec of Starknet storage, and provide tests.

- [ ] Change List to Vec
- [ ] Add test of the Vec change

**Comment by wheval** [comment]
Hello @MSghais , Can i work on this?

**Comment by casweeney** [comment]
Hello @MSghais I have looked at the contract, the logic is mostly in the `lock_manager.cairo` file.

- I will update the codebase from using `alexandria_storage::list::{List, ListTrait}` to use `Vec<T>` instead.
- I will update the test cases following the contract changes and ensure all tests are passing.
- Using `Vec<T>` will require using a more recent Starknet version as the current code base uses `starknet = "2.4.3"`

## ETA: 24 - 48 hours approximately.

**Comment by manlikeHB** [comment]
Hi @MSghais, can I work on this? 

ETA - 1 day.
