### ISSUE TITLE
Commit reveal scheme for Encrypted data onchain

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#355]
# Description

Do a commit reveal scheme for encrypted cairo data on chain.

Let's discuss it before if you want to be assigned. Ping me on Telegram.

- [ ] Create a Component for CommitRevealScheme
- [ ] Add necessary functions for abstract CRS. Let's discuss it

**Comment by blessingbytes** [comment]
i would love to take up this task

**Comment by Bosun-Josh121** [comment]
I am applying to this issue via OnlyDust platform.

My background and how it can be leveraged:

software engineering background, backend & smart contract dev with contribution to similar tasks(https://app.onlydust.com/u/Bosun-Josh121) looking to make  contribution on this project

I would create component & functions as required and would be sure to
work on feedback & recommendation ensuring contact.  I am willing to take on this challange

**Comment by 1nonlypiece** [comment]
Hi,  
I’d like to work on this issue as I have experience with Cairo and building on StarkNet, including writing and optimizing smart contracts.  

ETA:  
I estimate completing this task in about 12-24 hours. Let me know if I can get started!

**Comment by MooreTheAnalyst** [comment]
I'd be happy to do this.

**Comment by ShantelPeters** [comment]
Can I jump on this task?

**Comment by suhas-sensei** [comment]
i can say i have some experience in writing cairo contracts so maybe ill try creating that component under the scheme, but i need some more details regarding this. Hoping to discuss this if assigned.

**Comment by Supa-mega** [comment]
May I take care of this?

**Comment by DuendexCR** [comment]
I’m interested in this one.

**Comment by tosinmoses384** [comment]
Can I be assigned to this?

**Comment by Dorcas18** [comment]
I'd love to give this a go.

**Comment by 3th-Enjay** [comment]
Can I take this issue?

**Comment by jaiminRaiyani** [comment]
Would love to tackle this!

**Comment by Amarjeet325** [comment]
May I be assigned to this?

**Comment by guha-rahul** [comment]
can i take this up?

**Comment by guha-rahul** [comment]
Can i take this up?
