### ISSUE TITLE
Fix NestJS indexer Railway issue deployment with Docker

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#357]
# Description

Indexer Apibara in NestJS is located in apps/nestjs-indexer.

We deploy it on Railway with the railway.indexer.json config in the Root and the corresponding Docker.

Deployment issue when building the indexer-prisma, used also in data-backend

- [ ] Fix deployment on Railway with Docker 
- [ ] Add CI/CD for nestjs-indexer and maybe  indexer-prisma build and import

**Comment by ncoquelet** [comment]
Mind if I take this issue?

ETA 24h
