### ISSUE TITLE
Refacto AFK contract call with SDK and React SDK

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#363]
# Description

We need to refacto our functions call with an Account in params so we can use Starknet and Telegram Argent Account in both context.
Also it can be used to be integrated and plan to be publish as a package (afk_sdk and afk_react_sdk)

# Tasks
- [ ] refacto the call (without react) in afk_sdk
- [ ] refacto the hooks etc in afk_react_sdk, need to be compatible for NextJS and Expo

# Needed for

Start call these in PWA and Pixel package

Check if we can stop the PWA with Pixel easily deployed and use in Expo

**Comment by caxtonacollins** [comment]
I am a Full Stack Developer with two years of professional experience, specializing in web3. I have strong background in blockchain and extensive experience in Next.js/React, TypeScript, and Cairo.

I will like to take care of this. Will follow the above requirements and create a good PR within 24hours.

**Comment by addegbenga** [comment]
I’d like to work on this.
Eta 24hrs
