### ISSUE TITLE
Hooks & Utils for Nostr private message

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#38]
Create utils and hooks for Private messages between users in DM, with encryption.
Do it in the packages/afk_nostr_sdk.

Needed for #37 

Hooks : 

- useSendPrivateMessage
- encryptedMessage
- decryptMessage

NIP details here:

https://github.com/nostr-protocol/nips/blob/master/17.md

https://github.com/nostr-protocol/nips/blob/master/44.md

https://github.com/nostr-protocol/nips/blob/master/59.md

**Comment by martinvibes** [comment]
i

**Comment by ikemHood** [comment]
can i take this?

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged

Hi @MSghais 

I can work on the "Hooks & Utils for Nostr Private Messaging #38" issue. My name is Benjamin, and I have 3 years of experience with Next.js, TypeScript, and frontend development. I’ve worked on various projects, including those on OnlyDust, where I tackled complex UI and component challenges.

### How I plan on tackling this issue
The goal is to create utilities and hooks for handling private messages between users with encryption. This involves developing hooks for sending messages and utilities for encrypting and decrypting messages in compliance with NIPs 17, 44, and 59.

#### Create `useSendPrivateMessage` Hook

- **Functionality:** I will develop the `useSendPrivateMessage` hook to manage sending encrypted private messages. It will handle creating Rumor and Seal events, encrypting them, and wrapping them in a Gift Wrap.
- **Details:** The hook will take the message content and the recipient’s public key as inputs, then encrypt the message and send it.

#### Develop `encryptedMessage` Utility

- **Functionality:** I will create the `encryptedMessage` utility to handle encryption of messages using NIP-44 algorithms.
- **Details:** It will take the message content, the sender’s private key, and the recipient’s public key, then return the encrypted message.

#### Implement `decryptMessage` Utility

- **Functionality:** I will develop the `decryptMessage` utility for decrypting messages that have been encrypted.
- **Details:** It will take the encrypted message content and the recipient’s private key, and return the decrypted message.

### Testing and Validation

- **Local Testing:** I will ensure that all utilities and hooks function correctly with mock data and simulated scenarios.
- **Integration Testing:** I will test the integration of these components to confirm they work seamlessly together.

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hi MSG, please let me work on this.

### How I plan on tackling this issue
To solve this issue, I'd:
1. I'll set up Encryption Utilities( I'll install a cryptographic library (e.g., crypto-js). I'll create functions to encrypt and decrypt messages.
2. I'll create hooks to manage private messages, integrating the encryption functions.
3. Lastly, I'll integrate NIP Standards, I'll ensure compliance with NIP-17 and NIP-44 standards for message format and encryption.

Please let me work on this ASAP.

**Comment by addegbenga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
My background and how it can be leveraged:
Frontend engineer with 5+ years experience in software development


### How I plan on tackling this issue
How I plan on tackling this issue:
-Going through nips MD
-Utilising tanstack query to manage the newly created hooks.

ETA: in 42hrs

**Comment by Gift-Naomi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I am a web3/frontend developer

### How I plan on tackling this issue
1. **Develop Utility Functions**: Create utility functions in `packages/afk_nostr_sdk` for encrypting and decrypting private messages based on NIP-17, NIP-44, and NIP-59. These functions will handle the encryption of outgoing messages and decryption of incoming messages.

2. **Implement React Hooks**: Develop `useSendPrivateMessage`, `encryptedMessage`, and `decryptMessage` hooks to simplify the process of sending encrypted messages and decrypting received messages in Direct Messages (DMs) between users.

3. **Integration and Documentation**: Integrate these utilities and hooks into the SDK, ensuring they are well-documented for ease of use in the application, with references to the relevant NIPs.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have experience with frontend development and integrating secure messaging systems. My background in building and managing hooks and utilities, along with knowledge of encryption practices, will ensure that the private messaging features are implemented effectively and securely.

### How I plan on tackling this issue
1. **Review NIPs**: Understand encryption and messaging protocols from NIP-17, NIP-44, and NIP-59.
2. **Implement Utils**: Create utility functions for encrypting and decrypting messages.
3. **Build Hooks**: Develop `useSendPrivateMessage` to handle sending encrypted messages.
4. **Test and Integrate**: Ensure the functionality works correctly and integrates with the DM system in `afk_nostr_sdk`.
