### ISSUE TITLE
Hooks for Private group

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#39]
Create hooks and utils Private groups with Admin management.
Related to #32 

Add the hooks and utils in the packages/afk_nostr_sdk.

Hooks : 

- useCreateGroup

Admins:
- useGroupEditMetadata
- useAddMember
- useDeleteEvent
- useRemoveMember
- useAddPermission
- useRemovePermission

Users:
- useSendGroupMessage

NIP details here:

https://github.com/nostr-protocol/nips/blob/master/29.md

**Comment by ikemHood** [comment]
h

**Comment by Jemiiah** [comment]
I would to work on this issue

**Comment by Gift-Naomi** [comment]
Hi @MSghais  I will love to work on this

**Comment by addegbenga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

My background and how it can be leveraged:
Frontend engineer with 5+ years experience in software development

How I plan on tackling this issue:
-Going through  [nips md](https://github.com/nostr-protocol/nips/blob/master/29.md) 
-Utilising tanstack query to manage the newly created hooks.

**Comment by MSghais** [comment]
> Hi @MSghais I will love to work on this

Do you have an ETA please?
