### ISSUE TITLE
Fix Login Nostr and Modal

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#395]
- [ ] Fix modal Login
- [ ] Fix mnemonic when login
- [ ] Fix create account
- [ ] Fix navigation modal (maybe render only components)

**Comment by ekumamatthew** [comment]
I’d like to help with this.

**Comment by NueloSE** [comment]
I’d like to help with this.

**Comment by OWK50GA** [comment]
### Hi, I'm Wilfrid Okorie, a Frontend Web Developer and I'd like to take this issue

Expect my first PR within 24 hours of assignment

**Comment by lindsaymoralesb** [comment]
To fix navigation inside modal -> replace navigation with render (new modal module)
Use bip39 library to fix mnemonic issues that will fix login, create account and import keys issues

ETA: 6hours (done :P) PR already created, please assign

**Comment by Supa-mega** [comment]
May I take care of this?

**Comment by OthmanImam** [comment]
Can I take this issue?
