### ISSUE TITLE
Private key import on Profile screen

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#5]
Get the possibility to retrieve your private key:

- [ ] Modal/Form to retrieve your private key
- [ ] Add this on the Profile 
- [ ] Password enter to retrieve private key

If you forgot to copy down the private key after creating the account, which was unable to recover (get again) from settings  The share and about button in the profile page isnt clickable

**Comment by Jemiiah** [comment]
I would love to work on this issue @MSghais

**Comment by Jemiiah** [comment]
Hello @MSghais I have made over 25+ contributions on OnlyDust to different projects and still presenting contributing to other project this would be my first time contributing to this projects I would love the privilege to work with you on this project and work on as many issues as possible. I’m a frontend a developer as well as a web3 developer it would give me the delight to get assigned this issue 🚀🚀

**Comment by GoSTEAN** [comment]
I am applying this issue via [OnlyDust Platform](https://app.onlydust.com/p/afk---aligned-fam-kernel)

**Comment by Jemiiah** [comment]
> Gm @Jemiiah, thank you for applying!
> 
> We are going to postpone this issue for a few days or 2 weeks max, and we announce when it's ready!
> 
> Stay tuned and join the Telegram group to stay up to date: https://t.me/afk_aligned_fam_kernel

Hello sir...lets do this
