### ISSUE TITLE
Token name Tip modal not visible

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#6]
Issue: Tokens names are not visible until I clicked.

Steps to Reproduce:

Navigate to the section with token buttons.
Observe the buttons not being visible until clicked.

- [ ] Colors in dark mode for the token name
- [ ] Check if the selected token is visible
- [ ] Button visible by default
- [ ] Navigate to the section with token buttons

![image](https://github.com/user-attachments/assets/c5327dd8-ead4-4f92-863a-af9d5b7a3309)

**Comment by CristopherAguilar10** [comment]
Hello @MSghais, can i work on this issue? I would like to help

**Comment by martinvibes** [comment]
hello @MSghais i would love to work on this issue and participate

**Comment by MSghais** [comment]
Gm @CristopherAguilar10 and @martinvibes 

We are going to postpone this issue for a few days or 2 weeks max, and we announce when it's ready!
Cool features etc to test in a few :)

Stay tuned and join the Telegram group to stay up to date:
https://t.me/afk_aligned_fam_kernel

**Comment by martinvibes** [comment]
okay @MSghais till then, would love to contribute by the time the issue is open for contribution 🙃

**Comment by MSghais** [comment]
Gm everyone, the OD Hack on Only Dust is starting tomorrow!

A lot of issues are incoming, stay tuned and join the TG group:
https://t.me/afk_aligned_fam_kernel
