### ISSUE TITLE
Fix backend Golang

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#79]
- [ ] Fix Backend GOlang backend
- [ ] to not use configs/backend.config.Json and configs/prod-backend.config.json
- [ ] Verify if it's answering well in the Website UI /pixel
- [ ] Check if pixel etc are correctly saved

**Comment by EjembiEmmanuel** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
@MSghais I'd love to work on this 

ETA: <1 hour
