### ISSUE TITLE
Nostr deposit tip with Solidity using Kakarot Dual VM Lib

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#83]
# Description

Tip contract Solidity call Dual VM are located here:
https://github.com/AFK-AlignedFamKernel/afk_monorepo/blob/95d302756a1e5d6630fda1888f961f44b6d30116/onchain/solidity_contracts/src/nostr/DepositEscrowNostr.sol#L8

We have an issue with felt252 conversion in Solidity to a uint256 calldata.
We need to fix this issue to finish the test for the claim deposit one:

Check namespace.cairo call.

Test dualvm are located here:
https://github.com/AFK-AlignedFamKernel/afk_monorepo/blob/95d302756a1e5d6630fda1888f961f44b6d30116/onchain/tests/TipNostr.test.ts#L34

Todo
- [ ] Check deposit.cairo functions to do in Solidity.
- [ ] get_deposit()
- [ ] deposit()
- [ ] claim()
- [ ] cancel()
- [ ] Write dual test for Solidity and Cairo. Check example in test/DualVmToken.test.ts

**Comment by ScottyDavies** [comment]
@can i take up this issue?

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I’m experienced in creating and integrating functions across different blockchain platforms and writing comprehensive dual tests

### How I plan on tackling this issue
I will examine how it interacts with the Solidity contract and identify necessary get and write functions.

Implement Functions in Solidity:
get_deposit(): Fetch deposit information.
deposit(): Handle deposit operations.
claim(): Implement claim logic.
cancel(): Add cancellation functionality.

Create Dual Tests:
 Write tests to validate functionality in both Solidity and Cairo, using test/DualVmToken.test.ts as a reference.

Verify Integration:
 Ensure seamless interaction between Cairo and Solidity contracts through rigorous testing and validation.

**Comment by MSghais** [comment]
@ScottyDavies please join the TG group and ping me in telegram as I said 10 times..

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I have experience both in Solidity and Cairo testing.

### How I plan on tackling this issue
I will carefully read and understand the current test suite and implement all the necessary coverage needed as well as fix the problem regarding felt252/uint256 conversion.
