### ISSUE TITLE
Desktop right sidebar

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#85]
## Description

Add Desktop right sidebar for Trending quests etc

- [ ] Only available in Desktop
- [ ] Create a RightSidebar screen, some implementation are in the layout already
- [ ] Add TABS for this Right bar:  Trending, Quests.
- [ ] Add some data as examples using Nostr hooks, Launchpad hooks etc
- [ ] Add Right sidebar to the Router.ts and navigator for Main, Degen etc
- [ ] Add this in the Router.ts component maybe (some impl have been try to add two DrawerNavigator)

**Comment by lauchaves** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
Hey! I'm Lau Chaves, and I would like to contribute to this issue!
I have over 5 years of experience with JavaScript, ReactJS,React Native TypeScript, and Ruby. I’m now enthusiastic about web3 and eager to learn more! I’m also a member of Dojo Coding Costa Rica. 


### How I plan on tackling this issue
Id follow these steps:

- Create a new screen: Make a new screen called "RightSidebar".
Use existing layout: Some parts of the layout might already be helpful.
Add tabs: Create tabs for "Trending" and "Quests".
Use sample data: Ill get example data from Nostr and Launchpad.
Add sidebar to router
