### ISSUE TITLE
Fix apps/indexer Apibara and Endpoints

### ISSUE THREAD

**Issue by MSghais** [AFK-AlignedFamKernel/afk_monorepo#97]
- [ ] Verify events of the contract in the launchpad_types.cairo
- [ ] Verify the variables, data saved, etc
- [ ] Run all indexers in the docker file
- [ ] Test them with Docker to have the same env as in prod
- [ ] Check Launchpad events and init.sql tables
- [ ] Call the endpoints of the apps/data-backend to check if events are saved

**Comment by EjembiEmmanuel** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/afk---aligned-fam-kernel).

### My background and how it can be leveraged
I'd love to work on this 

ETA: before EOD
